//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 就业服务中心管理员账号类.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




private class 就业服务中心管理员账号类 {
	private Object serviceID;
	public void setServiceID(int ID) {
	
	}
	
	public int getServiceID() {
	
	}
}
