//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 就业指导书信息类.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




private class 就业指导书信息类 {
	private Object 就业指导书信息;
}
