//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 总查询界面类.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




public class 总查询界面类 {
	private Object 学生信息;
	private Object 用人单位信息;
	private Object 面试结果信息;
	public void 显示学生信息() {
	
	}
	
	public void 显示用人单位信息() {
	
	}
	
	public void 显示面试结果信息() {
	
	}
}
