//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 招聘信息界面类.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




public class 招聘信息界面类 {
	public void 显示招聘信息() {
	
	}
}
