//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 招聘信息.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




public class 招聘信息 {
	private Object 招聘岗位;
	private Object 招聘人数;
	private Object 招聘要求;
}
