//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 毕业生实体类.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




public class 毕业生实体类 {
	private Object ID;
	private Object name;
	private Object major;
	private Object grade;
	public void setID(int ID) {
	
	}
	
	public int getID() {
	
	}
	
	public void setName(String name) {
	
	}
	
	public String getName() {
	
	}
	
	public void setMajor(String major) {
	
	}
	
	public String getMajor() {
	
	}
	
	public void setGrade(String grade) {
	
	}
	
	public String getGrade() {
	
	}
}
