//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 毕业生登录界面类.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




public class 毕业生登录界面类 {
	private Object 个人信息;
	public void 查询毕业生信息() {
	
	}
}
