//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 毕业生编辑个人信息界面类.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




private class 毕业生编辑个人信息界面类 {
	private Object 毕业生个人信息;
	public void 显示用户个人信息() {
	
	}
	
	public void 修改信息获取() {
	
	}
}
