//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 用人单位信息.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




public class 用人单位信息 {
	private Object comID;
	private Object tel;
	private Object name;
	private Object field;
	private Object address;
	public void setComID(int comID) {
	
	}
	
	public int getComID() {
	
	}
	
	public void setTel(String tel) {
	
	}
	
	public String getTel() {
	
	}
	
	public void setName(String name) {
	
	}
	
	public String getName() {
	
	}
	
	public void setField(String field) {
	
	}
	
	public String getField() {
	
	}
	
	public void setAddress(String address) {
	
	}
	
	public String getAddress() {
	
	}
}
