//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 登录控制类.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




public class 登录控制类 {
	public void 获取信息() {
	
	}
	
	public void 查询信息() {
	
	}
}
