//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 管理学生面试结果界面类.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




public class 管理学生面试结果界面类 {
	private Object 学生面试信息;
	public void 显示面试结果() {
	
	}
	
	public void 查询面试结果() {
	
	}
}
