//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 统计学生信息界面类.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




public class 统计学生信息界面类 {
	private Object 学生信息;
	public void 显示学生信息() {
	
	}
	
	public void 查询学生信息() {
	
	}
}
