//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 统计学生信息控制类.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




public class 统计学生信息控制类 {
	public void 获取信息() {
	
	}
	
	public void 读取信息() {
	
	}
}
