//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 编辑用人单位信息界面类.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




public class 编辑用人单位信息界面类 {
	private Object 用人单位信息;
	public void 显示用人单位信息() {
	
	}
	
	public void 修改信息() {
	
	}
	
	public void 获取信息() {
	
	}
}
