//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 获取信息控制类.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




public class 获取信息控制类 {
	private Object 获取学生信息;
	private Object 获取面试结果信息;
	private Object 获取用人单位信息;
	private Object 获取就业服务中心管理员账号信息;
	public void 获取信息() {
	
	}
}
