//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 辅导员类.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




public class 辅导员类 {
	private Object conID;
	private Object name;
	private Object major;
	private Object grade;
	public void setConID(int conID) {
	
	}
	
	public int getConID() {
	
	}
	
	public void setName(String name) {
	
	}
	
	public String getName() {
	
	}
	
	public void setMajor(String major) {
	
	}
	
	public String getMajor() {
	
	}
	
	public void setGrade(String grade) {
	
	}
	
	public String getGrade() {
	
	}
}
