//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 雇主类.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




public class 雇主类 {
	private Object empID;
	private Object name;
	private Object email;
	private Object tel;
	public void setEmpID(int empID) {
	
	}
	
	public int getEmpID() {
	
	}
	
	public void setName(String name) {
	
	}
	
	public String getName() {
	
	}
	
	public void setEmail(String email) {
	
	}
	
	public String getEmail() {
	
	}
	
	public void setTel(String tel) {
	
	}
	
	public String getTel() {
	
	}
}
