//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 面试结果类.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




public class 面试结果类 {
	private Object result;
	public void setResult(String result) {
	
	}
	
	public String getResult() {
	
	}
}
