//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 无标题


//  @ File Name : 面试结果查询界面.java
//  @ Date : 2023/7/6
//  @ Author : 
//
//




public class 面试结果查询界面 {
	private Object 面试结果信息;
	public void 显示面试结果() {
	
	}
}
